name: Execute python script to create github issue

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v1        

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Create github issue
        env:
            GITHUB_TOKEN: ${{ secrets.GRIDEA }}
        run: |
          pip install requests
          cd tools/自动创建评论
          python GtalkComment.py ${GITHUB_TOKEN}
